# Generated by Django 2.1.7 on 2019-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('PRE', 'prepaid'), ('POS', 'postpaid')], max_length=128)),
                ('phone_number', models.CharField(max_length=12)),
                ('operator', models.CharField(max_length=20)),
                ('circle', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=8)),
            ],
        ),
    ]
