# Generated by Django 2.1.7 on 2019-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='service',
            field=models.CharField(choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=128),
        ),
    ]
