# Generated by Django 2.1.7 on 2019-04-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0005_remove_mobile_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='number',
            new_name='phone_number',
        ),
    ]
