# Generated by Django 2.1.7 on 2019-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0006_auto_20190403_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='amount',
            field=models.SmallIntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='phone_number',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
