# Generated by Django 2.1.7 on 2019-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0007_auto_20190403_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='amount',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
