# Generated by Django 2.1.7 on 2019-04-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0008_auto_20190403_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile',
            new_name='mobiles',
        ),
    ]
