# Generated by Django 2.1.7 on 2019-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0009_auto_20190404_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='service_type',
            field=models.CharField(default=-1, max_length=12),
            preserve_default=False,
        ),
    ]
