# Generated by Django 2.1.7 on 2019-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0011_auto_20190404_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='service_type',
            field=models.CharField(max_length=128),
        ),
    ]
