# Generated by Django 2.1.7 on 2019-04-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0012_auto_20190404_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='service_type',
            field=models.CharField(choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=128),
        ),
    ]
