# Generated by Django 2.1.7 on 2019-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0013_auto_20190404_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='service_type',
            field=models.BooleanField(default=False),
        ),
    ]
