# Generated by Django 2.1.7 on 2019-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0015_auto_20190405_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='service_type',
            field=models.CharField(max_length=128),
        ),
    ]
