# Generated by Django 2.1.7 on 2019-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0016_auto_20190405_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='dthcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dthoperator', models.CharField(max_length=128)),
                ('custmoerid', models.CharField(max_length=128)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
