# Generated by Django 2.1.7 on 2019-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0018_auto_20190406_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='dthcard',
            name='amount',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
