# Generated by Django 2.1.7 on 2019-04-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0019_dthcard_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dthcard',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='dthcard',
            old_name='dthoperator',
            new_name='operator',
        ),
    ]
