# Generated by Django 2.1.7 on 2019-04-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0020_auto_20190406_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dthcard',
            old_name='amount',
            new_name='dthamount',
        ),
        migrations.RenameField(
            model_name='dthcard',
            old_name='customer',
            new_name='dthcustomer',
        ),
        migrations.RenameField(
            model_name='dthcard',
            old_name='operator',
            new_name='dthoperator',
        ),
    ]
