# Generated by Django 2.1.7 on 2019-04-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0021_auto_20190406_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dthcard',
            old_name='dthamount',
            new_name='dth_amount',
        ),
        migrations.RenameField(
            model_name='dthcard',
            old_name='dthcustomer',
            new_name='dth_customer',
        ),
        migrations.RenameField(
            model_name='dthcard',
            old_name='dthoperator',
            new_name='dth_operator',
        ),
    ]
