# Generated by Django 2.1.7 on 2019-04-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0022_auto_20190406_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dthcard',
            new_name='dthcardform',
        ),
    ]
