# Generated by Django 2.1.7 on 2019-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0024_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name_on_card',
            field=models.CharField(max_length=256),
        ),
    ]
