# Generated by Django 2.1.7 on 2019-04-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0026_eletricity'),
    ]

    operations = [
        migrations.CreateModel(
            name='gasprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_provider', models.CharField(max_length=128)),
                ('bp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
