# Generated by Django 2.1.7 on 2019-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0027_gasprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='datacard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=128)),
                ('phone_number', models.BigIntegerField()),
                ('operator', models.CharField(max_length=20)),
                ('circle', models.CharField(max_length=20)),
                ('amount', models.SmallIntegerField()),
            ],
        ),
    ]
