# Generated by Django 2.1.7 on 2019-04-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0028_datacard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datacard',
            new_name='datacardform',
        ),
    ]
