# Generated by Django 2.1.7 on 2019-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0031_landlineform'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadbandform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadband_operator', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
