# Generated by Django 2.1.7 on 2019-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywave', '0032_broadbandform'),
    ]

    operations = [
        migrations.CreateModel(
            name='metroform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_operator', models.CharField(max_length=128)),
                ('metro_number', models.CharField(max_length=20)),
            ],
        ),
    ]
