# Generated by Django 2.1.7 on 2019-04-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wallet',
            new_name='wallet_amount',
        ),
    ]
