# Generated by Django 2.1.7 on 2019-04-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190413_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wallet_amount',
            new_name='wallet_act',
        ),
    ]
