# Generated by Django 2.1.7 on 2019-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190413_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_act',
            name='wallet_amount',
            field=models.IntegerField(),
        ),
    ]
