# Generated by Django 2.1.7 on 2019-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190414_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_act',
            name='t_amount',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
