# Generated by Django 2.1.7 on 2019-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wallet_act_t_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='commondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('circle', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.SmallIntegerField(blank=True, null=True)),
                ('dth_operator', models.CharField(blank=True, max_length=128, null=True)),
                ('dth_customer', models.CharField(blank=True, max_length=128, null=True)),
                ('dth_amount', models.IntegerField(blank=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=128, null=True)),
                ('elec_customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('gas_provider', models.CharField(blank=True, max_length=128, null=True)),
                ('bp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('water_operator', models.CharField(blank=True, max_length=128, null=True)),
                ('wnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('landline_operator', models.CharField(blank=True, max_length=128, null=True)),
                ('broadband_operator', models.CharField(blank=True, max_length=128, null=True)),
                ('metro_operator', models.CharField(blank=True, max_length=128, null=True)),
                ('metro_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
