# Generated by Django 2.1.7 on 2019-04-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_commondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commondata',
        ),
    ]
